demo:
  orderservice:
    version: 0.0.1

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  protocol:
    port: -1