server:
  port: 80

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true

netty:
  websocket:
    # Websocket????
    port: 1024
    # ?????
    ip: 0.0.0.0
    # ???????
    max-frame-size: 10240
    # URI??
    path: /channel
